mode: parallel
containers:
  - address:
    username:
    password:
    client_id:
    client_secret:
    weigth:
    mode: parallel
    limit: 9999
theme:
static:
master:
database:
qywx_key:
daily_push:
resident:
user_agent:
telegram_bot_token:
telegram_user_id:
qquid:
qqgid:
qbot_public_mode: true
default_priority:
no_ghproxy: false
daily_asset_push_cron:
Wskey: true  # 填空默认禁用wskey转换 需要的填true
AtTime: 7 #填写1-12之间的数  填错自负默认为10  10点容易出现高峰超时。
IsAddFriend: #填写true或者false  false
tasks:
  - cron: 0 6 * * *
    path: https://raw.githubusercontent.com/cdle/xdd/main/scripts/jd_goodMorning.js
    enable: true
    word: 早起福利
    mode: obo
  - cron: 0 0 * * *
    path: https://raw.githubusercontent.com/cdle/xdd/main/scripts/jd_angryBean.js
    enable: true
    word: 抢京豆
    mode: alo
    envs:
      - name: angryBeanPins
      - value: jd_xxxxx&jd_ooooo
